CREATE OR REPLACE FUNCTION DO_AUTO_DELETE_FUNC()
RETURNS TRIGGER AS 
$$
BEGIN
    DELETE FROM mtl_norms mn
    WHERE mn.op_id = OLD.op_id AND mn.det_id = OLD.det_id;
    RETURN OLD;
END
$$
LANGUAGE plpgsql;

CREATE TRIGGER DO_AUTO_DELETE
BEFORE DELETE
ON labor_norms
FOR EACH ROW
EXECUTE PROCEDURE DO_AUTO_DELETE_FUNC();
