CREATE OR REPLACE FUNCTION UOM_AUTO_UPDATE_FUNC()
RETURNS TRIGGER AS 
$UOM_AUTO_UPDATE_FUNC$
BEGIN
    UPDATE mtl_norms 
    SET uom = NEW.mtl_uom
    WHERE mtl_norms.mtl_id = NEW.mtl_id;
    RETURN NULL;
END
$UOM_AUTO_UPDATE_FUNC$
LANGUAGE plpgsql;

CREATE TRIGGER UOM_AUTO_UPDATE
AFTER UPDATE
ON materials
FOR EACH ROW
EXECUTE PROCEDURE UOM_AUTO_UPDATE_FUNC();
